/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AgentesIaRouteImport } from './routes/agentes-ia'
import { Route as IndexRouteImport } from './routes/index'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesIaRoute = AgentesIaRouteImport.update({
  id: '/agentes-ia',
  path: '/agentes-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRoute
  '/promocoes': typeof PromocoesRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRoute
  '/promocoes': typeof PromocoesRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRoute
  '/promocoes': typeof PromocoesRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes-ia'
    | '/automacoes'
    | '/campanhas'
    | '/clientes'
    | '/promocoes'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes-ia'
    | '/automacoes'
    | '/campanhas'
    | '/clientes'
    | '/promocoes'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/agentes-ia'
    | '/automacoes'
    | '/campanhas'
    | '/clientes'
    | '/promocoes'
    | '/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesIaRoute: typeof AgentesIaRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CampanhasRoute: typeof CampanhasRoute
  ClientesRoute: typeof ClientesRoute
  PromocoesRoute: typeof PromocoesRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes-ia': {
      id: '/agentes-ia'
      path: '/agentes-ia'
      fullPath: '/agentes-ia'
      preLoaderRoute: typeof AgentesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesIaRoute: AgentesIaRoute,
  AutomacoesRoute: AutomacoesRoute,
  CampanhasRoute: CampanhasRoute,
  ClientesRoute: ClientesRoute,
  PromocoesRoute: PromocoesRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
